####################PROMETHEUS####################
version: "3.9"

services:
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
#      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - t4y
####################PROMETHEUS####################
