version: "3.9"

services:
  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - ./log:/var/log
    links:
      - loki
#    ports:
#      -
    command:
      - '-config.file=/mnt/config/promtail-config.yaml'
    restart: always
    networks:
      - t4y