version: "3.9"

services:
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - 3100:3100
    command:
      - '-config.file=/mnt/config/loki-config.yaml'
    restart: always
    networks:
      - t4y