version: "3.9"

name: monitor_core

networks:
  t4y:
    external: true
#   ipam:
#     config:
#      - subnet: 192.168.1.0/24


services:
####################PROMETHEUS####################
  prometheus:
    extends:
      file: prometheus/prometheus-compose.yaml
      service: prometheus
####################PROMETHEUS####################

####################GRAFANA#######################
  grafana:
    extends:
      file: grafana/grafana-compose.yaml
      service: grafana
####################GRAFANA#######################

####################NODE_EXPORTER#################
  node_exporter:
    extends:
      file: node_exporter/node_exporter-compose.yaml
      service: node_exporter
####################NODE_EXPORTER#################

####################LOKI##########################
  loki:
    extends:
      file: loki/loki-compose.yaml
      service: loki
####################LOKI##########################

####################TEMPO#########################
  tempo:
    extends:
      file: tempo/tempo-compose.yaml
      service: tempo
####################TEMPO#########################
